### PR TITLE
fix type errors in lsp.esbonio

### PR DESCRIPTION
**Pull request by danieleades**
CAUTION: this is untested.

- addresses type errors using `namespace-packages` mypy flag
- fix type errors (`self.rst.app.confdir` is an error, since `rst` has no attribute `app`)
- use `pathlib.Path` to represent paths, rather than using strings

### CODE REVIEW

**Comment by danieleades** [comment]
ping @haiyangToAI

**Review by haiyangToAI — APPROVED** [review]
Overall looks good, test cases passed.

For the namespace_packages change, isn't it used when import packages don't have an __init__.py file? 

In our case, esbonio.lsp.rst does actually have __init__.py, but CompletionContext is defined inside __init__.py. This can be fixed by this: from esbonio.lsp.rst.__init__ import CompletionContext.

However, for that mypy error: [misc], I have no idea how to fix that.

So in general, I will take the change. Thanks.

**Comment by iSOLveIT** [comment]
Hi, @danwos, @danieleades, and @haiyangToAI, 
After merging this PR into `master`, some test cases are failing.
```
=========================== short test summary info ============================
FAILED tests/test_lsp/test_lsp.py::test_need_directive_snippets_completion[client0]
FAILED tests/test_lsp/test_lsp.py::test_need_directive_role_completion[client0]
FAILED tests/test_lsp/test_lsp.py::test_need_id_selection_completion[client0]
FAILED tests/test_lsp/test_lsp.py::test_need_auto_generated_id_completion[client0]
FAILED tests/test_lsp/test_lsp.py::test_goto_definition[client0] - IndexError...
FAILED tests/test_lsp/test_lsp.py::test_hover[client0] - AssertionError: asse...
=================== 6 failed, 90 passed in 73.72s (0:01:13) ====================
```
This is from PR #630.  Thanks

**Comment by danwos** [comment]
Hi @iSOLveIT 
Thanks for the hint.

@haiyangToAI is already on it and created PR #632 to fix them / revert some changes.

**Pull request merged**
