### PR TITLE
Adds the missing trailing slash for url of needservice

### PR DESCRIPTION
**Pull request by twodrops**

### CODE REVIEW

**Comment by twodrops** [comment]
Is there a more elegant way of doing this?

**Comment by danwos** [comment]
Thanks for the PR.
You could also use `` if self.url[-1] != "/":`` or  ``if not self.url.endswith("/"):``.
Both untested, but should work.
Do you want to update your PR to one of the above solutions?

**Comment by danwos** [comment]
And if you like, add your name to our AUTHORS file :) 
Thanks for your contribution :+1:

**Comment by danwos** [comment]
If possible please add also ``Fixes #187`` in the commit message.
So the issue is automatically linked to the commit and gets also closed, if PR is merged.

**Comment by twodrops** [comment]
I find what @ubmarco mentioned with `join` methods a better way than checking for a missing trailing slash

**Comment by twodrops** [comment]
> And if you like, add your name to our AUTHORS file :)

@danwos It will be a privilege to add my name to AUTHORS. Thanks for the offer. I will do it as soon as I make a substantial contribution :)

**Comment by danwos** [comment]
Close this, as the given comments get introduced by #237

**Pull request closed without merging**
