### PR TITLE
remove python2 compatibility code and tidy imports in `tests` directory

### PR DESCRIPTION
**Pull request by danieleades**

### CODE REVIEW

**Comment by danieleades** [comment]
i'm assuming `pathlib2` should also be removed from the test-requirements?

**Comment by danieleades** [comment]
note: for consistency, imports have been sorted using [isort](https://pypi.org/project/isort/)

**Comment by danwos** [comment]
Close & reopen to trigger travis

**Comment by danieleades** [comment]
> sphinxcontrib.needs.services.github.NeedGithubServiceException: GitHub: API rate limit exceeded (twice). Stop here.

**Comment by danwos** [comment]
Argh shit, that's because of the new "needservice" feature, which loads data from github.
And github only allows a certain amount of requests.

As I have just triggered so many parallel builds, maybe it exceeded the rate limit quite fast.
I need a better solution here (stubbing the requests by monkepatches.) 
Created #183 for this.

**Comment by danieleades** [comment]
rebase on master

**Comment by danwos** [comment]
And again, thanks for all your effort!
Makes the code much cleaner.

**Pull request merged**
