### PR TITLE
Consolidate logging

### PR DESCRIPTION
**Pull request by danieleades**
The import logic for the logging is slightly complex and causes false positives for linters.

This pull request consolidates this import logic so it only occurs in *one place*

### CODE REVIEW

**Comment by danieleades** [comment]
@danwos is this of interest?

**Comment by danwos** [comment]
Sorry for not giving any attention to this PR, which definitely deserves it.
I'm a little bit busy these days.
I will try to review it in the next days.

**Comment by danwos** [comment]
Thanks for this PR and cleaning up the code :+1: 

There is only one point which is personal don't like much: relative imports.

Would it be possible to change it to ``from sphinxcontrib.needs.logging import getLogger``?

And if not done already in one of your other PRs, feel free to put you name in the CONTRIBUTOR list.

**Comment by danwos** [comment]
Close & reopen to trigger travis.

**Comment by danieleades** [comment]
> There is only one point which is personal don't like much: relative imports.
> 
> Would it be possible to change it to from sphinxcontrib.needs.logging import getLogger?

no problem, will update

**Comment by danieleades** [comment]
rebase and update imports

**Comment by danwos** [comment]
One last rebase and we are done :)
Thanks for optimizing the logging of sphinx-needs.

**Comment by danwos** [comment]
I added the WIP-extension, to allow PRs to be in WIP-status (work in progress) by setting it in the title.
If present, a merge is blocked.
Much better as the GitHub internal Draft status, which I often miss and merge then by mistake.

**Comment by danieleades** [comment]
rebased on master

**Comment by danieleades** [comment]
@danwos i notice that you haven't used a squash merge for those last few pull requests- that's going to make the commit history pretty 'noisy'. would you prefer if i squashed the commits in these pull requests *first*?

**Comment by danwos** [comment]
No, I was not sure if a squash merge maybe removes you as committer and only my names shows up  (as I created/initiated the squash merge). I don't want  to steal any appreciations :)

I even like squash commits much more. So I will try it with the next ones.
Thanks for the hint.

**Pull request merged**
