### PR TITLE
Resolves issue #61 by ensuring dashes are replaced with underscores

### PR DESCRIPTION
**Pull request by tlovett**
This should resolve the issue I reported in #61.

### CODE REVIEW

**Comment by tlovett** [comment]
After playing with this some more, I realized there are a number of characters that exhibit the same behavior.  I'll update this up to replace all of these characters to underscores.

**Comment by tlovett** [comment]
OK, pushed changed to replace all invalid characters

**Comment by danwos** [comment]
Thanks for fixing this.
Do you need a single release for this?
Otherwise I would wait till some of #56, #57, #58 were realized.

**Comment by tlovett** [comment]
No, no need for an immediate release.

**Pull request merged**
