### PR TITLE
Issue-413 Fix generating needpie and needbar images in source folder

### PR DESCRIPTION
**Pull request by Youcef-DZ**
Fix sphinx-needs generating a needpie image in source folder

#413

### CODE REVIEW

**Comment by danwos** [comment]
Thanks a lot for the PR, it looks great.

Can you add also a small note to the changelog.rst file about the bug fix?
And also feel to add your name to the AUTHORS file.

**Comment by Youcef-DZ** [comment]
Thank you for looking into this, just noticed that needbar had the same issue and updated that as well.

**Comment by danwos** [comment]
Thanks for the PR.
Looks great and got merged :+1:

**Comment by arwedus** [comment]
uh oh. I get this error using the new master:

```
WARNING: cannot copy image file '/home/.../src/_images/need_pie_401bf.png': [Errno 2] No such file or directory: '/home/.../src/_images/need_pie_401bf.png'
```

**Comment by danwos** [comment]
Thanks for testing :+1: 

The sphinx-needs docs are looking good: 
https://sphinxcontrib-needs.readthedocs.io/en/latest/directives/needpie.html

@arwedus:  Have you tested it from a clean build?

**Comment by Youcef-DZ** [comment]
> uh oh. I get this error using the new master:
> 
> ```
> WARNING: cannot copy image file '/home/.../src/_images/need_pie_401bf.png': [Errno 2] No such file or directory: '/home/.../src/_images/need_pie_401bf.png'
> ```

Looks like somewhere in the code we are trying to copy the pie image from the source directory. My change no longer generate images in the source directory, outdir only.  Need your help to see where this warning is coming from and change it to use outdir.

**Comment by arwedus** [comment]
> Thanks for testing 👍
> 
> The sphinx-needs docs are looking good: https://sphinxcontrib-needs.readthedocs.io/en/latest/directives/needpie.html
> 
> @arwedus: Have you tested it from a clean build?

GitHub Actions do not purge the source tree. Try a local build with a clean checkout. That's what I did to try this feature. If you don't delete the pie image in the source tree and just don't regenerate it, you will have no obvious issues of course

**Comment by danwos** [comment]
I undo this change with PR #500.

Let's put the discussion back to the original issue #413.
So reasons and a new proposal can be found there.

**Pull request merged**
